matrix:
  VERSION:
    - "0.3.9"

steps:
  docker-build:
    # https://woodpecker-ci.org/plugins/Docker%20Buildx
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: harbor.nkl.st/${CI_REPO,,}
      registry: harbor.nkl.st
      tags: latest,${VERSION}
      cache_from:
        - "type=registry\\,ref=harbor.nkl.st/${CI_REPO,,}"
      build_args:
        - VERSION=${VERSION}
      username:
        from_secret: harbor_user
      password:
        from_secret: harbor_password
