matrix:
  VERSION:
    - "0.4.0"

steps:
  docker-build:
    # https://woodpecker-ci.org/plugins/Docker%20Buildx
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: harbor.nkl.st/${CI_REPO,,}
      registry: harbor.nkl.st
      tags: latest,${VERSION}
      # Can't use that because of https://codeberg.org/woodpecker-plugins/docker-buildx/issues/70
      # cache_from:
      #   - "type=registry,ref=harbor.nkl.st/${CI_REPO,,}:${VERSION}"
      build_args:
        - VERSION=${VERSION}
      username:
        from_secret: harbor_user
      password:
        from_secret: harbor_password
