name: Docker

on:
  push:
    branches: ["main"]

env:
  LATEST_VERSION: "0.4.3"

jobs:
  docker-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        VERSION: ["0.4.0", "0.4.1", "0.4.2", "0.4.3"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/niklasrosenstein/jagrosh-musicbot-docker:latest
            ${{ env.LATEST_VERSION == 'latest' && format('ghcr.io/niklasrosenstein/jagrosh-musicbot-docker:latest', matrix.VERSION) || '' }}
          build-args: |
            VERSION=${{ matrix.VERSION }}
          cache-from: |
            type=registry,ref=ghcr.io/niklasrosenstein/jagrosh-musicbot-docker:${{ matrix.VERSION }}
